services:
  my-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: note-noise
    env_file:
      - .env
    ports:
      - "1314:1314"
    volumes:
      - ./data:/app/data
    environment:
      - LOG_LEVEL=info
      # 数据库配置（默认使用 SQLite）
      - DB_TYPE=sqlite
      - DB_PATH=/app/data/noise.db
      # PostgreSQL 配置（可选）
      #- DB_TYPE=postgres
      #- DB_HOST=postgres
      #- DB_PORT=5432
      #- DB_USER=postgres
      #- DB_PASSWORD=
      #- DB_NAME=noise
      # MySQL 配置（可选）
      #- DB_TYPE=mysql
      #- DB_HOST=mysql
      #- DB_PORT=3306
      #- DB_USER=
      #- DB_PASSWORD=
      #- DB_NAME=
    restart: unless-stopped

  # PostgreSQL 服务（可选）
  #postgres:
  #  image: postgres:latest
  #  environment:
  #    - POSTGRES_USER=postgres
  #    - POSTGRES_PASSWORD=
  #    - POSTGRES_DB=noise
  #  volumes:
  #    - postgres_data:/var/lib/postgresql/data

  # MySQL 服务（可选）
  #mysql:
  #  image: mysql:8
  #  environment:
  #    - MYSQL_ROOT_PASSWORD=
  #    - MYSQL_DATABASE=noise
  #  volumes:
  #    - mysql_data:/var/lib/mysql

#volumes:
#  postgres_data:
#  mysql_data: